{
    "current_shuffled_witnesses": [
        "genesis",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "current_virtual_time": "0",
    "hardfork_required_witnesses": 17,
    "id": 0,
    "majority_version": "0.0.0",
    "max_runner_witnesses": 1,
    "max_voted_witnesses": 19,
    "median_props": {
        "account_creation_fee": "0.000 TTR",
        "maximum_block_size": 131072,
        "dollar_interest_rate": 1000
    },
    "miner_weight": 1,
    "next_shuffle_block_num": 1,
    "num_scheduled_witnesses": 1,
    "timeshare_weight": 5,
    "top20_weight": 1,
    "witness_pay_normalization_factor": 25
}