#include <zattera/protocol/get_config.hpp>
#include <zattera/protocol/config.hpp>
#include <zattera/protocol/asset.hpp>
#include <zattera/protocol/types.hpp>
#include <zattera/protocol/version.hpp>
#include <zattera/protocol/runtime_config.hpp>

namespace zattera { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_MODE
   result[ "IS_TEST_MODE" ] = true;
   result["TEST_MODE_BLOCK_LIMIT"] = TEST_MODE_BLOCK_LIMIT;
#else
   result[ "IS_TEST_MODE" ] = false;
#endif
   result["ZATTERA_CHAIN_ID"] = zattera::protocol::get_chain_id();
   result["ZATTERA_CHAIN_ID_NAME"] = zattera::protocol::get_chain_id_name();
   result["ZATTERA_ADDRESS_PREFIX"] = zattera::protocol::get_address_prefix();
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["ZTR_SYMBOL"] = ZTR_SYMBOL;
   result["ZBD_SYMBOL"] = ZBD_SYMBOL;
   result["ZATTERA_INITIAL_VOTE_POWER_RATE"] = ZATTERA_INITIAL_VOTE_POWER_RATE;
   result["ZATTERA_REDUCED_VOTE_POWER_RATE"] = ZATTERA_REDUCED_VOTE_POWER_RATE;
   result["ZATTERA_100_PERCENT"] = ZATTERA_100_PERCENT;
   result["ZATTERA_1_PERCENT"] = ZATTERA_1_PERCENT;
   result["ZATTERA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = ZATTERA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["ZATTERA_ACTIVE_CHALLENGE_COOLDOWN"] = ZATTERA_ACTIVE_CHALLENGE_COOLDOWN;
   result["ZATTERA_ACTIVE_CHALLENGE_FEE"] = ZATTERA_ACTIVE_CHALLENGE_FEE;
   result["ZATTERA_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = ZATTERA_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["ZATTERA_BANDWIDTH_PRECISION"] = ZATTERA_BANDWIDTH_PRECISION;
   result["ZATTERA_BLOCKCHAIN_PRECISION"] = ZATTERA_BLOCKCHAIN_PRECISION;
   result["ZATTERA_BLOCKCHAIN_PRECISION_DIGITS"] = ZATTERA_BLOCKCHAIN_PRECISION_DIGITS;
   result["ZATTERA_BLOCKCHAIN_HARDFORK_VERSION"] = ZATTERA_BLOCKCHAIN_HARDFORK_VERSION;
   result["ZATTERA_BLOCKCHAIN_VERSION"] = ZATTERA_BLOCKCHAIN_VERSION;
   result["ZATTERA_BLOCK_INTERVAL"] = ZATTERA_BLOCK_INTERVAL;
   result["ZATTERA_BLOCKS_PER_DAY"] = ZATTERA_BLOCKS_PER_DAY;
   result["ZATTERA_BLOCKS_PER_HOUR"] = ZATTERA_BLOCKS_PER_HOUR;
   result["ZATTERA_BLOCKS_PER_YEAR"] = ZATTERA_BLOCKS_PER_YEAR;
   result["ZATTERA_CASHOUT_WINDOW_SECONDS"] = ZATTERA_CASHOUT_WINDOW_SECONDS;
   result["ZATTERA_COMMENT_REWARD_FUND_NAME"] = ZATTERA_COMMENT_REWARD_FUND_NAME;
   result["ZATTERA_CONTENT_CONSTANT"] = ZATTERA_CONTENT_CONSTANT;
   result["ZATTERA_CONTENT_REWARD_PERCENT"] = ZATTERA_CONTENT_REWARD_PERCENT;
   result["ZATTERA_CONVERSION_DELAY"] = ZATTERA_CONVERSION_DELAY;
   result["ZATTERA_CREATE_ACCOUNT_DELEGATION_RATIO"] = ZATTERA_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["ZATTERA_CREATE_ACCOUNT_DELEGATION_TIME"] = ZATTERA_CREATE_ACCOUNT_DELEGATION_TIME;
   result["ZATTERA_CREATE_ACCOUNT_WITH_ZATTERA_MODIFIER"] = ZATTERA_CREATE_ACCOUNT_WITH_ZATTERA_MODIFIER;
   result["ZATTERA_DEFAULT_ZBD_INTEREST_RATE"] = ZATTERA_DEFAULT_ZBD_INTEREST_RATE;
   result["ZATTERA_FEED_HISTORY_WINDOW"] = ZATTERA_FEED_HISTORY_WINDOW;
   result["ZATTERA_FEED_INTERVAL_BLOCKS"] = ZATTERA_FEED_INTERVAL_BLOCKS;
   result["ZATTERA_GENESIS_TIME"] = ZATTERA_GENESIS_TIME;
   result["ZATTERA_HARDFORK_REQUIRED_WITNESSES"] = ZATTERA_HARDFORK_REQUIRED_WITNESSES;
   result["ZATTERA_INFLATION_RATE_START_PERCENT"] = ZATTERA_INFLATION_RATE_START_PERCENT;
   result["ZATTERA_INFLATION_RATE_STOP_PERCENT"] = ZATTERA_INFLATION_RATE_STOP_PERCENT;
   result["ZATTERA_INFLATION_NARROWING_PERIOD"] = ZATTERA_INFLATION_NARROWING_PERIOD;
   result["ZATTERA_CONTENT_REWARD_PERCENT"] = ZATTERA_CONTENT_REWARD_PERCENT;
   result["ZATTERA_VESTING_FUND_PERCENT"] = ZATTERA_VESTING_FUND_PERCENT;
   result["ZATTERA_MIN_REWARD_VESTING_SHARES"] = ZATTERA_MIN_REWARD_VESTING_SHARES;
   result["ZATTERA_BOOTSTRAP_FIXED_BLOCK_REWARD"] = ZATTERA_BOOTSTRAP_FIXED_BLOCK_REWARD;
   result["ZATTERA_BOOTSTRAP_SUPPLY_THRESHOLD"] = ZATTERA_BOOTSTRAP_SUPPLY_THRESHOLD;
   result["ZATTERA_GENESIS_WITNESS_NAME"] = ZATTERA_GENESIS_WITNESS_NAME;
   result["ZATTERA_GENESIS_PUBLIC_KEY_STR"] = ZATTERA_GENESIS_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["ZATTERA_GENESIS_PRIVATE_KEY"] = ZATTERA_GENESIS_PRIVATE_KEY;
#endif
   result["ZATTERA_INITIAL_SUPPLY"] = ZATTERA_INITIAL_SUPPLY;
   result["ZATTERA_ZBD_INITIAL_SUPPLY"] = ZATTERA_ZBD_INITIAL_SUPPLY;
   result["ZATTERA_IRREVERSIBLE_THRESHOLD"] = ZATTERA_IRREVERSIBLE_THRESHOLD;
   result["ZATTERA_MAX_ACCOUNT_NAME_LENGTH"] = ZATTERA_MAX_ACCOUNT_NAME_LENGTH;
   result["ZATTERA_MAX_ACCOUNT_WITNESS_VOTES"] = ZATTERA_MAX_ACCOUNT_WITNESS_VOTES;
   result["ZATTERA_MAX_ASSET_WHITELIST_AUTHORITIES"] = ZATTERA_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["ZATTERA_MAX_AUTHORITY_MEMBERSHIP"] = ZATTERA_MAX_AUTHORITY_MEMBERSHIP;
   result["ZATTERA_MAX_BLOCK_SIZE"] = ZATTERA_MAX_BLOCK_SIZE;
   result["ZATTERA_SOFT_MAX_BLOCK_SIZE"] = ZATTERA_SOFT_MAX_BLOCK_SIZE;
   result["ZATTERA_MAX_COMMENT_DEPTH"] = ZATTERA_MAX_COMMENT_DEPTH;
   result["ZATTERA_MAX_FEED_AGE_SECONDS"] = ZATTERA_MAX_FEED_AGE_SECONDS;
   result["ZATTERA_MAX_INSTANCE_ID"] = ZATTERA_MAX_INSTANCE_ID;
   result["ZATTERA_MAX_MEMO_SIZE"] = ZATTERA_MAX_MEMO_SIZE;
   result["ZATTERA_MAX_WITNESSES"] = ZATTERA_MAX_WITNESSES;
   result["ZATTERA_MAX_PERMLINK_LENGTH"] = ZATTERA_MAX_PERMLINK_LENGTH;
   result["ZATTERA_MAX_PROXY_RECURSION_DEPTH"] = ZATTERA_MAX_PROXY_RECURSION_DEPTH;
   result["ZATTERA_MAX_RATION_DECAY_RATE"] = ZATTERA_MAX_RATION_DECAY_RATE;
   result["ZATTERA_MAX_RESERVE_RATIO"] = ZATTERA_MAX_RESERVE_RATIO;
   result["ZATTERA_MAX_RUNNER_WITNESSES"] = ZATTERA_MAX_RUNNER_WITNESSES;
   result["ZATTERA_MAX_SATOSHIS"] = ZATTERA_MAX_SATOSHIS;
   result["ZATTERA_MAX_SHARE_SUPPLY"] = ZATTERA_MAX_SHARE_SUPPLY;
   result["ZATTERA_MAX_SIG_CHECK_DEPTH"] = ZATTERA_MAX_SIG_CHECK_DEPTH;
   result["ZATTERA_MAX_SIG_CHECK_ACCOUNTS"] = ZATTERA_MAX_SIG_CHECK_ACCOUNTS;
   result["ZATTERA_MAX_TIME_UNTIL_EXPIRATION"] = ZATTERA_MAX_TIME_UNTIL_EXPIRATION;
   result["ZATTERA_MAX_TRANSACTION_SIZE"] = ZATTERA_MAX_TRANSACTION_SIZE;
   result["ZATTERA_MAX_UNDO_HISTORY"] = ZATTERA_MAX_UNDO_HISTORY;
   result["ZATTERA_MAX_URL_LENGTH"] = ZATTERA_MAX_URL_LENGTH;
   result["ZATTERA_MAX_VOTE_CHANGES"] = ZATTERA_MAX_VOTE_CHANGES;
   result["ZATTERA_MAX_VOTED_WITNESSES"] = ZATTERA_MAX_VOTED_WITNESSES;
   result["ZATTERA_MAX_WITHDRAW_ROUTES"] = ZATTERA_MAX_WITHDRAW_ROUTES;
   result["ZATTERA_MAX_WITNESS_URL_LENGTH"] = ZATTERA_MAX_WITNESS_URL_LENGTH;
   result["ZATTERA_MIN_ACCOUNT_CREATION_FEE"] = ZATTERA_MIN_ACCOUNT_CREATION_FEE;
   result["ZATTERA_MIN_ACCOUNT_NAME_LENGTH"] = ZATTERA_MIN_ACCOUNT_NAME_LENGTH;
   result["ZATTERA_MIN_BLOCK_SIZE_LIMIT"] = ZATTERA_MIN_BLOCK_SIZE_LIMIT;
   result["ZATTERA_MIN_BLOCK_SIZE"] = ZATTERA_MIN_BLOCK_SIZE;
   result["ZATTERA_MIN_PERMLINK_LENGTH"] = ZATTERA_MIN_PERMLINK_LENGTH;
   result["ZATTERA_MIN_REPLY_INTERVAL"] = ZATTERA_MIN_REPLY_INTERVAL;
   result["ZATTERA_MIN_ROOT_COMMENT_INTERVAL"] = ZATTERA_MIN_ROOT_COMMENT_INTERVAL;
   result["ZATTERA_MIN_VOTE_INTERVAL_SEC"] = ZATTERA_MIN_VOTE_INTERVAL_SEC;
   result["ZATTERA_MIN_FEEDS"] = ZATTERA_MIN_FEEDS;
   result["ZATTERA_MIN_PAYOUT_ZBD"] = ZATTERA_MIN_PAYOUT_ZBD;
   result["ZATTERA_MIN_TRANSACTION_EXPIRATION_LIMIT"] = ZATTERA_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["ZATTERA_MIN_TRANSACTION_SIZE_LIMIT"] = ZATTERA_MIN_TRANSACTION_SIZE_LIMIT;
   result["ZATTERA_MIN_UNDO_HISTORY"] = ZATTERA_MIN_UNDO_HISTORY;
   result["ZATTERA_NULL_ACCOUNT"] = ZATTERA_NULL_ACCOUNT;
   result["ZATTERA_NUM_GENESIS_WITNESSES"] = ZATTERA_NUM_GENESIS_WITNESSES;
   result["ZATTERA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = ZATTERA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["ZATTERA_OWNER_AUTH_RECOVERY_PERIOD"] = ZATTERA_OWNER_AUTH_RECOVERY_PERIOD;
   result["ZATTERA_OWNER_CHALLENGE_COOLDOWN"] = ZATTERA_OWNER_CHALLENGE_COOLDOWN;
   result["ZATTERA_OWNER_CHALLENGE_FEE"] = ZATTERA_OWNER_CHALLENGE_FEE;
   result["ZATTERA_OWNER_UPDATE_LIMIT"] = ZATTERA_OWNER_UPDATE_LIMIT;
   result["ZATTERA_POST_AVERAGE_WINDOW"] = ZATTERA_POST_AVERAGE_WINDOW;
   result["ZATTERA_POST_REWARD_FUND_NAME"] = ZATTERA_POST_REWARD_FUND_NAME;
   result["ZATTERA_POST_WEIGHT_CONSTANT"] = ZATTERA_POST_WEIGHT_CONSTANT;
   result["ZATTERA_PROXY_TO_SELF_ACCOUNT"] = ZATTERA_PROXY_TO_SELF_ACCOUNT;
   result["ZATTERA_ZBD_INTEREST_COMPOUND_INTERVAL_SEC"] = ZATTERA_ZBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["ZATTERA_SECONDS_PER_YEAR"] = ZATTERA_SECONDS_PER_YEAR;
   result["ZATTERA_RECENT_RSHARES_DECAY_TIME"] = ZATTERA_RECENT_RSHARES_DECAY_TIME;
   result["ZATTERA_REVERSE_AUCTION_WINDOW_SECONDS"] = ZATTERA_REVERSE_AUCTION_WINDOW_SECONDS;
   result["ZATTERA_ROOT_POST_PARENT"] = ZATTERA_ROOT_POST_PARENT;
   result["ZATTERA_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = ZATTERA_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["ZATTERA_SAVINGS_WITHDRAW_TIME"] = ZATTERA_SAVINGS_WITHDRAW_TIME;
   result["ZATTERA_ZBD_START_PERCENT"] = ZATTERA_ZBD_START_PERCENT;
   result["ZATTERA_ZBD_STOP_PERCENT"] = ZATTERA_ZBD_STOP_PERCENT;
   result["ZATTERA_SOFT_MAX_COMMENT_DEPTH"] = ZATTERA_SOFT_MAX_COMMENT_DEPTH;
   result["ZATTERA_START_VESTING_BLOCK"] = ZATTERA_START_VESTING_BLOCK;
   result["ZATTERA_START_WITNESS_VOTING_BLOCK"] = ZATTERA_START_WITNESS_VOTING_BLOCK;
   result["ZATTERA_TEMP_ACCOUNT"] = ZATTERA_TEMP_ACCOUNT;
   result["ZATTERA_UPVOTE_LOCKOUT"] = ZATTERA_UPVOTE_LOCKOUT;
   result["ZATTERA_VESTING_WITHDRAW_INTERVALS"] = ZATTERA_VESTING_WITHDRAW_INTERVALS;
   result["ZATTERA_VESTING_WITHDRAW_INTERVAL_SECONDS"] = ZATTERA_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["ZATTERA_MIN_VOTE_VESTING_SHARES"] = ZATTERA_MIN_VOTE_VESTING_SHARES;
   result["ZATTERA_VOTE_DUST_THRESHOLD"] = ZATTERA_VOTE_DUST_THRESHOLD;
   result["ZATTERA_VOTE_REGENERATION_SECONDS"] = ZATTERA_VOTE_REGENERATION_SECONDS;
   result["ZATTERA_VIRTUAL_SCHEDULE_LAP_LENGTH"] = ZATTERA_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["ZATTERA_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = ZATTERA_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["ZATTERA_MAX_LIMIT_ORDER_EXPIRATION"] = ZATTERA_MAX_LIMIT_ORDER_EXPIRATION;
   result["ZATTERA_DELEGATION_RETURN_PERIOD"] = ZATTERA_DELEGATION_RETURN_PERIOD;

   return result;
}

} } // zattera::protocol
